name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show repo files (debug)
        run: dir

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "no requirements.txt"
          pip install pyinstaller

      - name: Build EXE (include templates & static)
        run: |
          echo "Building EXE..."
          pyinstaller --onefile --noconsole ^
            --add-data "templates;templates" ^
            --add-data "static;static" ^
            app.py
          echo "Build done."

      - name: Show dist folder (debug)
        run: dir dist || echo "dist missing"

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: IPPoolApp
          path: dist\app.exe
